/** body-muscles 肌群 id → 中文名称映射 */
export const MUSCLE_ZH: Record<string, string> = {
  head: '头部',
  face: '面部',
  'neck-left': '颈部左侧',
  'neck-right': '颈部右侧',
  'shoulder-front-left': '三角肌前束(左)',
  'shoulder-front-right': '三角肌前束(右)',
  'shoulder-side-left': '三角肌中束(左)',
  'shoulder-side-right': '三角肌中束(右)',
  'deltoid-rear-left': '三角肌后束(左)',
  'deltoid-rear-right': '三角肌后束(右)',
  'biceps-left': '肱二头肌(左)',
  'biceps-right': '肱二头肌(右)',
  'triceps-long-left': '肱三头肌长头(左)',
  'triceps-long-right': '肱三头肌长头(右)',
  'triceps-lateral-left': '肱三头肌外侧头(左)',
  'triceps-lateral-right': '肱三头肌外侧头(右)',
  'forearm-left': '前臂(左)',
  'forearm-right': '前臂(右)',
  'forearm-flexors-left': '前臂屈肌(左)',
  'forearm-flexors-right': '前臂屈肌(右)',
  'forearm-extensors-left': '前臂伸肌(左)',
  'forearm-extensors-right': '前臂伸肌(右)',
  'chest-upper-left': '胸大肌上部(左)',
  'chest-upper-right': '胸大肌上部(右)',
  'chest-lower-left': '胸大肌下部(左)',
  'chest-lower-right': '胸大肌下部(右)',
  'abs-upper-left': '腹直肌上部(左)',
  'abs-upper-right': '腹直肌上部(右)',
  'abs-lower-left': '腹直肌下部(左)',
  'abs-lower-right': '腹直肌下部(右)',
  'obliques-left': '腹斜肌(左)',
  'obliques-right': '腹斜肌(右)',
  'serratus-anterior-left': '前锯肌(左)',
  'serratus-anterior-right': '前锯肌(右)',
  'hip-flexor-left': '髋屈肌(左)',
  'hip-flexor-right': '髋屈肌(右)',
  'quads-left': '股四头肌(左)',
  'quads-right': '股四头肌(右)',
  'adductors-left': '髋内收肌(左)',
  'adductors-right': '髋内收肌(右)',
  'tibialis-anterior-left': '胫骨前肌(左)',
  'tibialis-anterior-right': '胫骨前肌(右)',
  'knee-left': '膝关节(左)',
  'knee-right': '膝关节(右)',
  'knee-back-left': '腘窝(左)',
  'knee-back-right': '腘窝(右)',
  'foot-left': '足(左)',
  'foot-right': '足(右)',
  'foot-back-left': '足跟(左)',
  'foot-back-right': '足跟(右)',
  'hand-left': '手(左)',
  'hand-right': '手(右)',
  'hand-back-left': '手背(左)',
  'hand-back-right': '手背(右)',
  'elbow-left': '肘(左)',
  'elbow-right': '肘(右)',
  'head-back': '头后部',
  nape: '项部',
  'traps-upper-left': '斜方肌上束(左)',
  'traps-upper-right': '斜方肌上束(右)',
  'traps-mid-left': '斜方肌中束(左)',
  'traps-mid-right': '斜方肌中束(右)',
  'traps-lower-left': '斜方肌下束(左)',
  'traps-lower-right': '斜方肌下束(右)',
  'lats-upper-left': '背阔肌上部(左)',
  'lats-upper-right': '背阔肌上部(右)',
  'lats-mid-left': '背阔肌中部(左)',
  'lats-mid-right': '背阔肌中部(右)',
  'lats-lower-left': '背阔肌下部(左)',
  'lats-lower-right': '背阔肌下部(右)',
  spine: '脊柱',
  'lower-back-erectors-left': '竖脊肌(左)',
  'lower-back-erectors-right': '竖脊肌(右)',
  'lower-back-ql-left': '腰方肌(左)',
  'lower-back-ql-right': '腰方肌(右)',
  'gluteus-medius-left': '臀中肌(左)',
  'gluteus-medius-right': '臀中肌(右)',
  'gluteus-maximus-left': '臀大肌(左)',
  'gluteus-maximus-right': '臀大肌(右)',
  'hamstrings-medial-left': '腘绳肌内侧(左)',
  'hamstrings-medial-right': '腘绳肌内侧(右)',
  'hamstrings-lateral-left': '腘绳肌外侧(左)',
  'hamstrings-lateral-right': '腘绳肌外侧(右)',
  'calves-gastroc-medial-left': '腓肠肌内侧头(左)',
  'calves-gastroc-medial-right': '腓肠肌内侧头(右)',
  'calves-gastroc-lateral-left': '腓肠肌外侧头(左)',
  'calves-gastroc-lateral-right': '腓肠肌外侧头(右)',
  'calves-soleus-left': '比目鱼肌(左)',
  'calves-soleus-right': '比目鱼肌(右)',
}

/** 肌群中文名，去除侧别后缀用于标签 chips */
export function muscleLabel(id: string): string {
  const name = MUSCLE_ZH[id] ?? id
  return name.replace(/\((左|右)\)$/, '')
}
